# Generated by Django 2.0 on 2018-01-27 18:34

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=300, null=True)),
                ('description', models.TextField(null=True)),
                ('chart_type', models.CharField(max_length=25, null=True)),
                ('rating', models.IntegerField(default=0)),
                ('popularity', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default={'labels': 'None', 'series': 'None'})),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='dataset',
            name='tags',
            field=models.ManyToManyField(to='dashboard.Tag'),
        ),
    ]
