# Generated by Django 2.0 on 2018-01-27 12:23

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='dataset',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'labels': 'None', 'series': 'None'}),
        ),
        migrations.AddField(
            model_name='dataset',
            name='url',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
