# Generated by Django 2.0 on 2018-01-27 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20180127_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dataset',
            name='tags',
            field=models.ManyToManyField(to='dashboard.Tag'),
        ),
    ]
