version: '2'
services:
  web:
    build: .
    container_name: dg04
    depends_on:
      - db
    volumes:
      - ./src:/src
  db:
    image: postgres:latest
    container_name: ps04
  scraper:
    build: .
    container_name: sp04
    depends_on:
      - web
    volumes:
      - ./src:/src
