version: '2'
services:
  web:
    build: .
    container_name: dg02
    depends_on:
      - db
      # - db_mongo
    volumes:
      - ./src:/src
  db:
    image: postgres:latest
    container_name: ps02
  # db_mongo:
    # image: mongo:latest
    # container_name: mg02
