version: '2'
services:
  web:
    command: bash -c "python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
  scraper:
    command: bash -c "cd scraper && scrapy crawl data_gov"
    ports:
      - "6023:6023"
